### ISSUE TITLE
Back button shows blank screen

### ISSUE THREAD

**Issue by pascalalfadian** [obedkristiaji/Dadoo-Lempar-Dadu-Virtual#6]
Hi @obedkristiaji & tim

Di Android saya, kalau aplikasinya dibuka, kemudian tekan back untuk close, itu dia masuk ke satu layar putih kosong dulu, dan baru tertutup kalau ditekan sekali lagi. Bisa tolong dicek, apakah di tempat kamu begitu juga? Dan jika iya, bisa tolong diperbaiki?

Trims;  
Pascal

**Comment by obedkristiaji** [comment]
Selamat malam Ko Pascal,

Untuk issue tersebut, terjadi juga di tempat kami, dan sudah kami perbaiki di commit terbaru, mungkin bisa coba untuk dicek kembali Ko. Selain itu juga saya menemukan ada bug di versi terbaru di playstore Ko, dimana link website informatikanya terpisah, setelah saya cek, ternyata terdapat kesalahan di file app/src/main/res/values/string.xml di string "url_informatika_unpar", di string tersebut, "https://informatika" dan ".unpar.ac.id" dipisahkan oleh spasi sehingga linknya menjadi terpisah di aplikasi.

Terimakasih Ko.

**Comment by pascalalfadian** [comment]
Sipp.. Thanks ya. Iya kemarin saya juga notice soal typo itu, cuma perbaikannya mesti di repo milik IF UNPAR. Sudah saya perbaiki dan saat ini ada di beta channel. Beberapa hari lagi saya rilis ke production kalau tidak ada masalah.

**Comment by obedkristiaji** [comment]
ohh oke Ko, thank you.
